Add a GitHub workflow
jrsoftware/issrc pull request #411
Opened 2022-01-24 10:08 UTC by dscho

This PR adds a GitHub workflow. Unfortunately, there is no version of Delphi available for direct download for use in CI builds. We have two options here:

- use a self-hosted runner with Delphi installed
- copy a minimal subset of Delphi's files onto the runner when building

The latter is less cumbersome to maintain, but due to reasons, we need to add a secret password to the repository and a secret URL to download the minimal issrc build environment. This minimal build environment was created by running the build locally while [the Process Monitor was running](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), then extracting the list of `.exe`, `.dll` and `.dcu` files that were used according to Process Monitor (not the most robust, but at least it results in a `.zip` file that only weighs ~7.5MB as opposed to naively zipping up all the files into a gigantic 1.2GB `.zip` file).

This GitHub workflow opens the door for asking contributors to test out fixes comfortably, merely by pointing them to build artifacts (which this PR does not yet add, as it is intended to gently ask whether this is a direction the InnoSetup maintainer(s) want to go?).

See https://github.com/dscho/issrc/actions/runs/1739134972 for an example how a successful run would look like.

2022-01-24 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jrsoftware/issrc?pullRequest=411) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jrsoftware/issrc?pullRequest=411) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jrsoftware/issrc?pullRequest=411) it.</sub>

2022-01-24 10:38 UTC, martijnlaan commented
Thanks. The Delphi build environment files such as .dcu's aren't redistributable are they? This would mean adding them to this repostistory anyway would be a violation of the Delphi license?

2022-01-24 18:42 UTC, dscho commented
> I could copy just a subset, as described e.g. here: https://delphi.fandom.com/wiki/Setting_up_a_Delphi_Build_Machine

I think that https://blogs.embarcadero.com/learn-about-delphi-continuous-integration-with-svn-jenkins-and-dunitx/ explicitly encourages a similar setup for Continuous Integration, too. That Embarcadero themselves advertise this setup suggests that they do _not_ even consider PR builds to constitute giving access to a third-party.

2022-01-24 18:57 UTC, dscho commented
And [this post](https://www.ideasawakened.com/post/getting-started-with-ci-cd-using-delphi-and-jenkins-on-windows) by a Delphi MVP suggests the following:

> Note that your Delphi license allows you to copy these files to a separate computer only for the sole use of performing automated builds.

And indeed, the [license agreement](https://www.embarcadero.com/products/rad-studio/rad-studio-eula?aldSet=en-GB) says this:

> 2.4. Command Line Compiler. Licensee may install the command line compiler on a separate computer from the Product itself, provided that the sole purpose of doing so is to allow that computer to perform unattended building of applications. The Command Line Compiler shall not be considered a 'redistributable'.

With that explicitly stated, I feel quite certain that the scheme I suggest is covered by Delphi's license agreement. (I am not a lawyer, of course...)

2022-01-25 08:23 UTC, martijnlaan commented
In the case that build artifiacts arent added to this repo I don't understand what this PR is aiming to achieve.

2022-01-25 08:30 UTC, dscho commented
Oh, we can totally attach build artifacts to the builds. I didn't do that yet in case you'd reject the entire idea of Continuous Integration.

What this PR currently does is just adding a way to verify that everything builds all right, and for licensing reasons this is done only via `push` but not `pull_request` events.

One might argue that it should also work for `pull_request` events, and that the Delphi license allows it under certain circumstances, but that's not how far this PR goes.

We could easily attach the build artifacts to these runs, if you're okay with that.

2022-01-25 08:48 UTC, martijnlaan commented
I don't know what you mean with adding artifacts to a 'build' or adding artifacts to a 'run', but adding them to this repo is definitely a no go and it's not clear to me whether this PR requires that or not.

2022-01-25 11:50 UTC, dscho commented
> I don't know what you mean with adding artifacts to a 'build' or adding artifacts to a 'run', but adding them to this repo is definitely a no go and it's not clear to me whether this PR requires that or not.

Let me try to clarify. There are a couple of different sets of files at play here:

- ***The source code***
  This is the set of files that you get when cloning https://github.com/jrsoftware/issrc (it contains more than just the source code, of course, as some pre-generated `.dll` and `.exe` files are part of that repository, too).
- ***The build output***
  This is the set of files that you get when running `./build.bat` (after setting up all the required `compilesettings.bat` files). This includes, but is not limited to, `Output/innosetup-*.exe`. Those are the ones most users will be interested in.
- ***The Delphi compiler***
  This is a set of files required to compile the Pascal source code into the final output. Typically, it is assumed that you have a working Delphi setup, but due to licensing restrictions, it can be a little bit of a hassle to get to one (in contrast to other products, _Delphi's_ Community Edition is hidden behind a "give us your email and we send a sales representative your way" wall).

What I mean by "build artifact" is the second set of files, the "build output", if you want. As far as I can see, there is no problem whatsoever to attach those to the build runs. Since I was not sure whether you are interested in Continuous Integration (and from your responses, I still receive no clarity about that), I did not want to put in the work just yet to figure out _what_ files to offer as build artifacts, [but now I did that work anyway](https://github.com/jrsoftware/issrc/pull/411/commits/c545051e3506c6e5fe421fff7b8fee692c913a29). [Here](https://github.com/dscho/issrc/actions/runs/1745117278) is an example of just that:

![image](https://user-images.githubusercontent.com/127790/150969850-776a0604-01d3-4e77-990e-4c015e3a347b.png)

You can download, say, the `installer.zip` file containing the compiler InnoSetup compiler by clicking on the `installer` artifact. Or the documentation as a `.zip` file by clicking on `ISHelp`.

What _would_ be a problem is if we added the third set of files, the Delphi compiler, to either the repository or to the build artifacts. Which is why I did not do that.

You will notice that the workflow [takes pains to download the Delphi compiler from a secret URL, as an encrypted `.zip` file, that is then unpacked using a secret passphrase](https://github.com/dscho/issrc/actions/runs/1745117278/workflow#L15-L25).

To make use of this workflow, you would therefore not only need to merge this PR, but also generate an encrypted `.zip` file from the same set of files from your own Delphi setup, upload it (e.g. to this PR as an attachment, as I did [over here](https://github.com/dscho/issrc/pull/1#issue-1112374032)), then add that URL as a [repository secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository), add the passphrase required to decrypt the `.zip` file as another repository secret, and then add `has-issrc-build-env` [to your repository topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).

If you do not want to make use of this workflow, but are okay with me and other contributors to make use of it, all you need is to merge this PR and then forget all about it.

2022-02-01 22:33 UTC, AdamKearn commented
> You will notice that the workflow [takes pains to download the Delphi compiler from a secret URL, as an encrypted `.zip` file, that is then unpacked using a secret passphrase](https://github.com/dscho/issrc/actions/runs/1745117278/workflow#L15-L25).

Can you not just get the download link from the website for the compiler...
And then have the GitHub Action download that using something like CURL on initialisation?

2022-02-01 22:35 UTC, dscho commented
> Can you not just get the download link from the website for the compiler...

@AdamKearn No, because Embarcadero does not offer the compiler for download via anonymous link. You have to register, personally, and IIRC a sales representative will send you a personalized link.

2022-02-01 23:16 UTC, AdamKearn commented
> a sales representative will send you a personalized link.

Ok and does that link ever expire?   Surely that link can be used as an ENV variable in the GitHub Actions.
That can then be used to download the compiler.

2022-02-02 06:50 UTC, dscho commented
> > a sales representative will send you a personalized link.
> 
> Ok and does that link ever expire? 

I believe it does expire at some stage.

Also note that there is no link to the compiler alone, only to the full RAD Studio.

Which is at the core of the problem with your suggestion.

> Surely that link can be used as an ENV variable in the GitHub Actions.

If the link was public, or if you were allowed to share it with others, sure. But neither is the case.

> That can then be used to download the compiler.

That would directly violate the license terms, which specifically prohibits licensees from letting a third-party use the software.

As I detailed earlier (with links and quotes, it took a long time to put together, please read it as carefully as I wrote it), in our context only installing for unattended builds is allowed. You still must take all precautions to _not_ violate the terms by making even only that compiler available to others, even inadvertently.

So I still believe that the approach I took is striking the best balance.

2022-02-02 08:38 UTC, martijnlaan commented
I'm OK with merging this but could you add a readme explaining how to set it up aimed at those who want to use it? This is now missing. Thanks in advance.

Note the merge would still take some time, I have to check the ISHelpGen commits that are also included, and skip the updated exe and instead do this myself.

2022-02-04 09:44 UTC, dscho commented
> I'm OK with merging this but could you add a readme explaining how to set it up aimed at those who want to use it? This is now missing. Thanks in advance.

[Done](https://github.com/jrsoftware/issrc/pull/411/commits/6de6043a389fec8dfecd28a836b525d30726e479).

> Note the merge would still take some time, I have to check the ISHelpGen commits that are also included, and skip the updated exe and instead do this myself.

Oh, there is not actually a _need_ to build and commit that `.exe`, I just included that to prove that the `ISHelpGen` commits lead to a fully-working build product. I dropped that commit.

Here is a [successful run](https://github.com/dscho/issrc/actions/runs/1794239756) of this new GitHub workflow.

2022-02-04 12:37 UTC, martijnlaan commented
Thanks. Is it possible to include license.txt in each artifact? And renamed installer to Output? I still see the ISHelpgen changes in this PR btw.

2022-02-04 12:40 UTC, martijnlaan requested changes

2022-02-04 12:40 UTC, martijnlaan commented on README.md
> +InnoSetup's source code includes a GitHub workflow that performs such unattended
Should say Inno Setup, so with a space

2022-02-04 12:40 UTC, martijnlaan commented on README.md
> +cd C:\Program Files (x86(\Embarcadero\Studio\20.0
Typo? Second ( should be a )?

2022-02-04 12:40 UTC, dscho commented
> I still see the ISHelpgen changes in this PR btw.

Yes, the changes are required to build with the current Delphi/MSXML. So I think we really still need those.

What I dropped was the committed `.exe`.

> Is it possible to include license.txt in each artifact?

Yes.

> And rename installer to Output?

Yes.

2022-02-04 12:40 UTC, martijnlaan commented on README.md
> +InnoSetup's source code includes a GitHub workflow that performs such unattended
Same thing a bit later btw

2022-02-04 12:42 UTC, martijnlaan commented
Why does it have to build ISHelpgen? Can't the workflow use the existing exe? I can see why building ISHelpgen is nice perhaps but it seems unrelated. Could be a separate PR though. One thing that would then have to change it that it would have to be part of build.bat, and not a separate step.

2022-02-04 12:50 UTC, dscho commented
> > Is it possible to include license.txt in each artifact?
> 
> Yes.
> 
> > And rename installer to Output?
> 
> Yes.

Done.

> Why does it have to build ISHelpgen?

Because I do not trust pre-commited `.exe` files in general. As a matter of fact, it is probably not the best practice to commit those artifacts in the first place.

> Could be a separate PR though.

Sure. But at some stage I run out of the time I can justify working on this... My main role is maintaining Git for Windows, after all, and my only beef here is that so far, I would not have been able to modify InnoSetup easily in case the Git for Windows installer requires it. So I've spent (actually way more than planned) time on getting a CI going, and am relatively happy with it. If at all, I would say that we should build _even more_ things in the CI build, not less. Things like `MyDll.dll` or `isbunzip.dll`.

But as I said, my time is a bit limited and I think that the current state really is pretty much good enough for now.

2022-02-05 21:52 UTC, dscho commented on README.md
> +InnoSetup's source code includes a GitHub workflow that performs such unattended
Fixed.

2022-02-05 21:52 UTC, dscho commented on README.md
> +cd C:\Program Files (x86(\Embarcadero\Studio\20.0
Fixed.

2022-03-31 20:11 UTC, merged

2022-03-31 20:13 UTC, martijnlaan commented
Did some fixes related to ISHelpGen and merged it. Let me know if they cause any problems. Thanks!

2022-04-05 16:29 UTC, dscho commented
> Did some fixes related to ISHelpGen and merged it. Let me know if they cause any problems. Thanks!

Looks good to me, thanks!